// AUTO-GENERATED by convert_to_js.py
// This is an EXAMPLE file with dummy data.
// Replace this by running: python convert_to_js.py

const GENERATED_AT = "2026-01-01 00:00:00";

const TIM_META = {
  "team_a": { "label": "Team A", "color": "#01696f" },
  "team_b": { "label": "Team B", "color": "#006494" },
  "team_c": { "label": "Team C", "color": "#7a39bb" }
};

const TIMELINE_DATA = [
  {
    "id": 0, "tim": "team_a", "program": "Annual Survey",
    "kegiatan": "Planning & Preparation",
    "jadwal_teks": "Jan – Feb 2026",
    "minggu_aktif": [1, 2, 3, 4, 5, 6, 7, 8, 9],
    "bulan_aktif": [1, 2]
  },
  {
    "id": 1, "tim": "team_a", "program": "Annual Survey",
    "kegiatan": "Field Data Collection",
    "jadwal_teks": "Mar – Jun 2026",
    "minggu_aktif": [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
    "bulan_aktif": [3, 4, 5, 6]
  },
  {
    "id": 2, "tim": "team_a", "program": "Annual Survey",
    "kegiatan": "Data Processing & Analysis",
    "jadwal_teks": "Jul – Sep 2026",
    "minggu_aktif": [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
    "bulan_aktif": [7, 8, 9]
  },
  {
    "id": 3, "tim": "team_a", "program": "Annual Survey",
    "kegiatan": "Report & Dissemination",
    "jadwal_teks": "Oct – Dec 2026",
    "minggu_aktif": [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53],
    "bulan_aktif": [10, 11, 12]
  },
  {
    "id": 4, "tim": "team_a", "program": "Ongoing Operations",
    "kegiatan": "Weekly Monitoring (Year-round)",
    "jadwal_teks": "Jan – Dec 2026",
    "minggu_aktif": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53],
    "bulan_aktif": [1,2,3,4,5,6,7,8,9,10,11,12]
  },
  {
    "id": 5, "tim": "team_b", "program": "Production Statistics",
    "kegiatan": "Q1 Data Collection",
    "jadwal_teks": "Jan – Mar 2026",
    "minggu_aktif": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    "bulan_aktif": [1, 2, 3]
  },
  {
    "id": 6, "tim": "team_b", "program": "Production Statistics",
    "kegiatan": "Q2 Data Collection",
    "jadwal_teks": "Apr – Jun 2026",
    "minggu_aktif": [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
    "bulan_aktif": [4, 5, 6]
  },
  {
    "id": 7, "tim": "team_b", "program": "Production Statistics",
    "kegiatan": "Q3 Data Collection",
    "jadwal_teks": "Jul – Sep 2026",
    "minggu_aktif": [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
    "bulan_aktif": [7, 8, 9]
  },
  {
    "id": 8, "tim": "team_b", "program": "Production Statistics",
    "kegiatan": "Q4 Data Collection",
    "jadwal_teks": "Oct – Dec 2026",
    "minggu_aktif": [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53],
    "bulan_aktif": [10, 11, 12]
  },
  {
    "id": 9, "tim": "team_b", "program": "Publication",
    "kegiatan": "Annual Report Publication",
    "jadwal_teks": "Dec 2026",
    "minggu_aktif": [49, 50, 51, 52, 53],
    "bulan_aktif": [12]
  },
  {
    "id": 10, "tim": "team_c", "program": "Administrative",
    "kegiatan": "Budget Planning",
    "jadwal_teks": "Jan 2026",
    "minggu_aktif": [1, 2, 3, 4, 5],
    "bulan_aktif": [1]
  },
  {
    "id": 11, "tim": "team_c", "program": "Administrative",
    "kegiatan": "Mid-Year Review",
    "jadwal_teks": "Jun – Jul 2026",
    "minggu_aktif": [23, 24, 25, 26, 27, 28],
    "bulan_aktif": [6, 7]
  },
  {
    "id": 12, "tim": "team_c", "program": "Administrative",
    "kegiatan": "Year-End Evaluation",
    "jadwal_teks": "Dec 2026",
    "minggu_aktif": [49, 50, 51, 52, 53],
    "bulan_aktif": [12]
  },
  {
    "id": 13, "tim": "team_c", "program": "Training",
    "kegiatan": "Staff Training Program",
    "jadwal_teks": "Mar – Apr 2026",
    "minggu_aktif": [10, 11, 12, 13, 14, 15, 16, 17, 18],
    "bulan_aktif": [3, 4]
  }
];
